# Generated by Django 4.1.7 on 2023-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='num',
            field=models.IntegerField(),
        ),
    ]
