# Generated by Django 4.1.7 on 2023-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_alter_hello_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='newtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
