# Generated by Django 4.1.7 on 2023-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_newtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtable',
            name='column1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newtable',
            name='column2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
